### ISSUE TITLE
v7: Massive log spam "Object .Gjs_lib_monitor_TopHatMeter (0x55b21f862060), has been already disposed — impossible to access it."

### ISSUE THREAD

**Issue by lkraav** [fflewddur/tophat#75]
Gnome 43 (latest minors), Gentoo Linux

After upgrading to v7, this triggers every second in journalctl

```
veebr 11 15:49:09 papaya gnome-shell[7617]: Object .Gjs_lib_monitor_TopHatMeter (0x55b21f862060), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
veebr 11 15:49:09 papaya gnome-shell[7617]: == Stack trace for context 0x55b21d8ca180 ==
veebr 11 15:49:09 papaya gnome-shell[7617]: #0   7ffdddb62120 b   /home/leho/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io/lib/monitor.js:506 (783018a2e20 @ 84)
veebr 11 15:49:09 papaya gnome-shell[7617]: #1   7ffdddb621d0 b   /home/leho/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io/lib/monitor.js:508 (783018a2e70 @ 12)
```

What went wrong?

**Comment by fflewddur** [comment]
Thanks for the report! I'm guessing a signal isn't being properly disconnected somewhere. Does this happen as soon as you log in, or does something trigger it? E.g., does it start after the computer wakes from sleep, or after the lock screen has appeared, or after a TopHat setting has been changed?

Also, which OS are you using and which version of GNOME?

**Comment by lkraav** [comment]
> Also, which OS are you using and which version of GNOME?

Added to issue opener.

> Does this happen as soon as you log in, or does something trigger it?

I think it triggers immediately after login, because I noticed in a fairly fresh session.

But will need to re-enable (and login dance on Wayland :disappointed:) and re-check.

**Comment by mattbdc** [comment]
15gb of log spam  too.  22.04.1LTS. This is on desktop left on permanently.

**Comment by fflewddur** [comment]
Thanks for the extra details! Are all of the stack traces consistently starting from monitor.js line 506?

**Comment by mattbdc** [comment]
Yes, to L506.

Feb  5 00:04:12 matt-nuci5 gnome-shell[1735]: Object .Gjs_lib_monitor_TopHatMeter (0x55e3364e5ca0), has been already disposed — impossible to access it. This mi
ght be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Feb  5 00:04:12 matt-nuci5 gnome-shell[1735]: == Stack trace for context 0x55e33009e170 ==
Feb  5 00:04:12 matt-nuci5 gnome-shell[1735]: #0   7ffd82a9fe80 b   /home/matt/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io/lib/monitor.js:506
 (2377bdb64150 @ 84)
Feb  5 00:04:12 matt-nuci5 gnome-shell[1735]: #1   7ffd82a9ff30 b   /home/matt/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io/lib/monitor.js:508

I don't recall enabling Show animations so probably not, unless it's the default.

**Comment by fflewddur** [comment]
Thanks again for reporting this! I just pushed out a release that should resolve the problem, but please let me know if you're still seeing these (or other) messages excessively in the system log.
