### ISSUE TITLE
CPU usage of the top processes is divided by core count.

### ISSUE THREAD

**Issue by hsiktas** [fflewddur/tophat#89]
Hello,

it seems like the CPU usage of the top processes is divided by core count.
On *nix systems, full load on a single core is always shown as 100% CPU load and the max load is `100% * (Number of Cores)`.
TopHat behaves like Windows here: full load on all cores together is shown as 100% and full load on a single core is shown as `100% / (Number of Cores)`.

Would it make sense to change the display of these top processes to the "*nix-way"? I think it is more intuitive, and it is easier to notice hanging processes at a single glance without doing these small calculations in the head.

**Comment by fflewddur** [comment]
This was a deliberate design decision on my part. If individual processes are measured per core, with one core's full use represented by 100%, you get multi-threaded processes using more than 100% of CPU. I wanted the overall processor utilization to be 0 - 100%, rather than 0 - [# of cores * 100]%.

I'll leave this issue open to see what other folks think. I could imagine this being a configurable preference.
